name: Fuzzing Action

on: ["push"]

jobs:
  Run-Fuzzer:
    name: running fuzz.py
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@Cody

      - run: pwd
      - run: ls