name: Fuzzing Action

on: ["push"]

jobs:
  Run-Fuzzer:
    name: running fuzz.py
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@main

      - run: python3 KubeSec-master/fuzz.py